workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: linux_medium  # Sửa từ linux_x2 thành linux_medium
    environment:
      groups:
        - android_sdk
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
